version: "1.0"
services:  
  postgres-kratos:
    image: postgres:16.3
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratosdb
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:Z"
    networks:
      - intranet
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - intranet
networks:
  intranet: