version: "1.0"
services:
  kratos-migrate:
    image: oryd/kratos:v1.2.0
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratosdb?sslmode=disable&max_conns=20&max_idle_conns=4&search_path=kratos123
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
  kratos:
    image: oryd/kratos:v1.2.0
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratosdb?sslmode=disable&max_conns=20&max_idle_conns=4&search_path=kratos123
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
networks:
  intranet: